PLAYSTATE_STOPPED = "stopped"
PLAYSTATE_PLAYING = "playing"
PLAYSTATE_PAUSED = "paused"
PLAYSTATE_RECORDING = "recording"
PLAYSTATE_RECORDPAUSED = "recordpaused"

FLAG_FOLDER = "folder"
FLAG_SELECTED = "selected"
FLAG_HAS_FX = "has-fx"
FLAG_MUTED = "muted"
FLAG_SOLOED = "soloed"
FLAG_SOLO_IN_PLACE = "solo-in-place"
FLAG_RECORD_ARMED = "record-armed"
FLAG_RECORD_MONITORING_ON = "record-monitoring-on"
FLAG_RECORD_MONITORING_AUTO = "record-monitoring-auto"
